/** Korte feedback na quiz (per les-slug). */
const LESSON_FEEDBACK: Record<string, string> = {
  'aromatische-druiven-white-wine:gewurztraminer': 'Goed.  Je herkent Gewürztraminer nu op:  - lychee   - rozen   - specerijen   - lage zuren   - volle body    Een extreem herkenbare druif in blindproeven.',
  'aromatische-druiven-white-wine:muscat': 'Goed.  Je begrijpt Muscat nu op:  - florale expressie   - druivigheid   - veelzijdige stijlen   - aromatische kracht',
  'aromatische-druiven-white-wine:pinot-gris': 'Goed.  Je begrijpt Pinot Gris nu op:  - stijlverschillen tussen landen   - textuur   - peer   - kruiden   - balans tussen fris en rijk    Belangrijk in blindvergelijkingen.',
  'aromatische-druiven-white-wine:torrontes': 'Goed.  Je herkent Torrontés nu op:  - bloemen   - citrus   - hoogte   - aromatische intensiteit',
  'aromatische-druiven-white-wine:vermentino': 'Goed.  Je beheerst nu de belangrijkste aromatische witte druiven.  Volgende stap:  **Module 7 — Service**',
  'belgische-stijlen-beer:abdijbier-vs-trappist': 'Sterk. Je begrijpt nu het hart van de Belgische biertraditie.',
  'belgische-stijlen-beer:dubbel': 'Goed gedaan. Je herkent nu de moutige diepte van Dubbel.',
  'belgische-stijlen-beer:quadrupel': 'Goed. Je herkent nu de intensiteit en rijpingswaarde van Quadrupel.',
  'belgische-stijlen-beer:saison': 'Sterk. Je begrijpt nu waarom Saison gastronomisch zo breed inzetbaar is.',
  'belgische-stijlen-beer:tripel': 'Sterk. Je begrijpt nu de balans tussen kracht en elegantie in Tripel.',
  'champagne-sparkling:blanc-de-blancs-vs-blanc-de-noirs': 'Goed.  Je begrijpt nu de stijlverschillen tussen deze twee klassieke Champagnecategorieën.  Belangrijkste leerpunten:  - Blanc de Blancs = elegantie - Blanc de Noirs = kracht - Druif bepaalt structuur',
  'champagne-sparkling:champagne-regio': 'Goed gedaan.  Je begrijpt nu hoe Champagne geografisch is opgebouwd en waarom terroir hier zo belangrijk is.  Belangrijkste leerpunten:  - Vier hoofdsubregio’s bepalen stijl - Krijtbodems zijn essentieel - Klimaat beïnvloedt zuur en rijping',
  'champagne-sparkling:druiven-van-champagne': 'Sterk.  Je kent nu de bouwstenen van Champagne.  Belangrijkste leerpunten:  - Chardonnay geeft spanning - Pinot Noir geeft kracht - Meunier geeft fruitigheid',
  'champagne-sparkling:prestige-cuvee': 'Sterk. Je hebt nu de kern van Champagne op Specialist-niveau.',
  'champagne-sparkling:vintage-vs-non-vintage': 'Sterk.  Je begrijpt nu het verschil tussen huisstijl en jaargangexpressie.  Belangrijkste leerpunten:  - NV draait om consistentie - Vintage draait om uitzonderlijk jaar - Vintage heeft vaak meer diepte',
  'cross-biodynamic:alcoholvrij-en-proefmomenten': 'Perfect. Je beheerst nu de cross-category toepassing van biodynamische timing.',
  'cross-biodynamic:barrel-aged-dranken': 'Perfect. Je begrijpt nu hoe barrel-aged dranken reageren.',
  'cross-biodynamic:bier-0-0-en-timing': 'Goed. Je begrijpt nu waarom alcoholvrije dranken extra gevoelig zijn.',
  'cross-biodynamic:bier-en-biodynamische-dagen': 'Sterk. Je begrijpt nu hoe bier biodynamisch anders kan aanvoelen.',
  'cross-biodynamic:cocktails-en-dagtypes': 'Sterk. Je begrijpt nu hoe cocktails biodynamisch beïnvloed kunnen worden.',
  'druivenrassen-rose-wine:cinsault': 'Sterk.  Je begrijpt nu waarom Cinsault finesse toevoegt.  Belangrijk:  - elegantie - florale tonen - lichte structuur',
  'druivenrassen-rose-wine:grenache': 'Goed.  Je begrijpt nu waarom Grenache de belangrijkste rosédruif ter wereld is.  Belangrijk:  - veel rood fruit - ronde textuur - basis van veel blends',
  'druivenrassen-rose-wine:mourvedre': 'Sterk.  Je begrijpt nu waarom Mourvèdre zo belangrijk is voor serieuze rosé.  Belangrijk:  - kracht - diepgang - rijpingspotentieel - gastronomische inzetbaarheid',
  'druivenrassen-rose-wine:syrah': 'Goed.  Je begrijpt nu hoe Syrah rosé krachtiger maakt.  Belangrijk:  - peperigheid - body - kleur - structuur',
  'druivenrassen-rose-wine:tempranillo-rosado': 'Sterk. Je begrijpt nu hoe druivenrassen roséstijl vormen.',
  'druivenrassen-wine:aromatische-druiven': 'Goed gedaan.  Je begrijpt nu wat aromatische druiven onderscheidt.  Belangrijkste leerpunten:  - aromatische druiven zijn direct herkenbaar in geur - bloemen en exotisch fruit zijn vaak dominant - deze druiven zijn vaak makkelijker blind te herkennen  Aromatische herkenning versnelt je proefontwikkeling.',
  'druivenrassen-wine:hoe-druiven-stijl-bepalen': 'Perfect. Je begrijpt nu hoe druiven de identiteit van wijn vormen.  Vanaf module 6 ga je leren waarom klimaat en terroir die identiteit verder vormen.',
  'druivenrassen-wine:neutrale-druiven': 'Goed gedaan.  Je begrijpt nu wat neutrale druiven uniek maakt.  Belangrijkste leerpunten:  - neutrale druiven tonen minder directe geurintensiteit - terroir speelt hier vaak een grotere rol - wijnmaker en klimaat beïnvloeden de stijl sterk  Neutrale druiven zijn essentieel om terroir te leren begrijpen.',
  'druivenrassen-wine:rode-druivenbasis': 'Goed gedaan.  Je begrijpt nu de belangrijkste rode basisdruiven.  Belangrijkste leerpunten:  - Cabernet Sauvignon geeft kracht en tannine - Merlot geeft zachtheid en rondheid - Pinot Noir geeft finesse en elegantie  Deze druiven vormen de kern van veel klassieke rode wijnen.',
  'druivenrassen-wine:witte-druivenbasis': 'Goed gedaan.  Je kent nu de belangrijkste witte basisdruiven.  Belangrijkste leerpunten:  - Chardonnay is veelzijdig en vaak neutraal - Sauvignon Blanc is fris en aromatisch - Riesling combineert hoge zuren met precisie  Deze drie vormen de basis van veel witte wijnstijlen.',
  'examen-beer-zero:0-0-ipa-vs-gewone-ipa': 'Sterk.  Je begrijpt nu waarom IPA blindproeven een geavanceerdere oefening is dan pils.',
  'examen-beer-zero:0-0-pils-vs-gewone-pils': 'Goed.  Je begrijpt nu hoe subtiele verschillen tussen gewone pils en 0.0 pils zichtbaar worden in body en afdronk.',
  'examen-beer-zero:praktijk-examen': 'Gefeliciteerd.  Je hebt de volledige Bier 0.0 Academy succesvol afgerond.  Je beheerst nu:  - productkennis - stijlherkenning - service - pairing - blindproeven  Je bent gecertificeerd op Master-niveau.',
  'examen-beer-zero:stijlherkenning-blind': 'Goed gedaan.  Je begrijpt nu hoe blindproeven jouw analysevaardigheid verdiept en objectiever maakt.',
  'examen-beer-zero:theorie-examen': 'Sterk.  Je bent klaar om jouw volledige kennisbasis te toetsen.  Dit is de theoretische afronding van jouw Bier 0.0 Academy.',
  'examen-beer:ipa-vs-stout-blind': 'Goed gedaan. Je herkent nu hop- versus roast-gedreven structuren blind.',
  'examen-beer:lager-vs-ale-blind': 'Sterk. Je kunt nu blind onderscheid maken tussen de basisfamilies van bier.',
  'examen-beer:theorie-praktijk-examen': 'Gefeliciteerd.  Je hebt Beer Academy succesvol afgerond.  **Eindniveau:** professioneel basisniveau bier   **Certificering:** Beer Explorer → Specialist → Master completed',
  'examen-biodynamic:theorie-examen-biodynamisch': 'Uitstekend. Je beheerst nu de volledige theoriebasis en bent klaar voor het praktijkdeel.',
  'examen-cocktails:cocktailstructuren-blind': 'Perfect. Je kunt nu cocktailfamilies blind analyseren op basis van structuur.',
  'examen-cocktails:spirit-blind-herkennen': 'Perfect. Je kunt nu cocktailfamilies blind analyseren op basis van structuur.',
  'examen-cocktails:theorie-praktijkexamen': 'Gefeliciteerd. Cocktail Academy succesvol afgerond.',
  'examen-port:blindproeven-ruby-vs-tawny': 'Sterk. Dit is de basis van Port blindproeven: jong fruit tegenover oxidatieve rijping herkennen.',
  'examen-port:blindproeven-vintage-vs-lbv': 'Sterk. Dit is één van de moeilijkste Port-blindtests. Als je deze beheerst, zit je op hoog specialistisch niveau.',
  'examen-port:praktijkexamen-port': 'Sterk. Dit is het moment waarop losse kennis verandert in echte Portvaardigheid.',
  'examen-port:theorie-examen-port': '### Beoordeling Je examen wordt beoordeeld op inhoudelijke juistheid, diepgang en praktische toepasbaarheid.  ### Wat je moet beheersen - Productie en fortificatie volledig begrijpen. - Stijlen en rijping kunnen onderscheiden. - Port professioneel kunnen adviseren in praktijk.',
  'examen-red-wine:merlot-vs-cabernet': 'Goed gedaan.  Je begrijpt nu beter:  - structuurverschillen - aromatische verschillen - hoe blends werken  Ga door naar de volgende les.',
  'examen-red-wine:pinot-noir-vs-nebbiolo': 'Goed gedaan.  Je begrijpt nu beter:  - hoe lichte kleur kan misleiden - hoe tannines doorslaggevend zijn - hoe blinddeductie werkt  Ga door naar de volgende les.',
  'examen-red-wine:red-wine-final-exam': 'Gefeliciteerd.  Je hebt de volledige **Red Wine Academy** afgerond.  Je beheerst nu:  - productie - proeven - druivenkennis - service - pairing - blindproeven  Volgende logische tracks binnen Way of Tasting:  → Witte Wijn Academy   → Rosé Academy   → Mousserende Wijn Academy   → Port Academy   → Bier Academy   → Cocktails Academy',
  'examen-rose-wine:provence-vs-tavel-blind': 'Sterk.  Je kunt nu Provence en Tavel blind beter onderscheiden.  Belangrijk:  - kleur is eerste indicator - body bevestigt stijl - kruidigheid en lengte maken vaak het verschil',
  'examen-rose-wine:rose-vs-lichte-rode-wijn-blind': 'Goed.  Je begrijpt nu hoe subtiel het verschil kan zijn tussen rosé en lichte rode wijn.  Belangrijk:  - tannine is sleutel - textuur geeft duidelijkheid - extractie bepaalt grip',
  'examen-rose-wine:theorie-praktijkexamen': 'Gefeliciteerd.  Je hebt het volledige Rosé-examen afgerond.  Belangrijk:  - fundament beheerst - productiemethoden begrepen - stijlen onderscheiden - druiven herkend - service toegepast - pairing geïntegreerd - blindanalyse uitgevoerd  Open examenstructuur correct behouden.  Geen multiple-choice quiz nodig.',
  'examen-sparkling:champagne-vs-cava-blind': 'Goed gedaan.  Je begrijpt nu hoe je Champagne en Cava blind logisch kunt analyseren.  Belangrijkste leerpunten:  - Zelfde methode, andere druiven - Terroir maakt verschil - Analyse is belangrijker dan gokken',
  'examen-sparkling:theorie-praktijkexamen': 'Gefeliciteerd.  Je hebt de Sparkling Wine Track afgerond.  Je beheerst nu:  - productie - proeven - service - pairing - blindanalyse  Dit vormt een sterke basis voor wijn, gastronomie en sommelierontwikkeling.',
  'examen-sparkling:traditioneel-vs-tank-blind': 'Sterk.  Je kunt nu traditionele methode en tankmethode blind beter onderscheiden.  Belangrijkste leerpunten:  - Traditioneel = meer autolyse - Tank = meer primair fruit - Structuur en mousse geven belangrijke hints',
  'examen-white-wine:chardonnay-vs-chenin-blind': 'Goed.  Je begrijpt nu:  ### Chardonnay  - ronder   - boter   - hout   - toast   - zachtere structuur    ### Chenin Blanc  - strakker   - hogere zuren   - honing   - spanning   - meer lineaire structuur    Dit onderscheid is cruciaal op Master-niveau.',
  'examen-white-wine:sauvignon-vs-riesling-blind': 'Goed.  Je begrijpt nu de belangrijkste blindverschillen:  ### Sauvignon Blanc  - groener   - gras   - kruisbes   - paprika   - agressiever aromatisch    ### Riesling  - strakker   - mineraler   - limoen   - petrol bij rijping   - puurdere zuurstructuur    Dit is één van de belangrijkste blindvergelijkingen binnen witte wijn.',
  'examen-white-wine:white-final-exam': 'Gefeliciteerd.  Je beheerst nu het volledige fundament van witte wijn:  - theorie   - productie   - druivenkennis   - service   - pairing   - blindproeven    Volgende logische tracks:  - :contentReference[oaicite:0]{index=0} Track   - Rode Wijn Track   - Mousserende Wijn Track   - Port Track   - Cocktails Track',
  'examen-wine:blindproeven-rood': 'Goed gedaan.  Je begrijpt nu hoe je rode wijn blind analyseert.  Belangrijkste leerpunten:  - tannine is een sterke indicator - kleur en body helpen stijl herkennen - structuur versnelt deductie  Rode blindproeverij vraagt sterke structuurkennis.',
  'examen-wine:blindproeven-wit': 'Goed gedaan.  Je begrijpt nu hoe je witte wijn blind analyseert.  Belangrijkste leerpunten:  - structuur is belangrijker dan alleen geur - hoge zuren zijn vaak sleutelindicatoren - deductie helpt druif en klimaat inschatten  Blindproeven begint altijd met observatie.',
  'examen-wine:wijn-eindexamen': 'Gefeliciteerd.  Je hebt de volledige basis van wijn afgerond.  Je begrijpt nu:  - hoe wijn wordt gemaakt - hoe wijn smaakt - hoe druiven werken - hoe terroir werkt - hoe service werkt - hoe pairing werkt - hoe blindproeven werkt  Je bent nu klaar voor verdieping in:  - Rode wijn - Witte wijn - Rosé - Mousserend - Versterkte wijn - Regionale masters',
  'frisse-druiven-white-wine:albarino': 'Goed.  Je herkent Albariño nu op:  - citrus   - zilt   - frisheid   - seafood-pairing',
  'frisse-druiven-white-wine:gruner-veltliner': 'Goed.  Je herkent Grüner nu op:  - peperigheid   - frisse zuren   - groene tonen   - gastronomische breedte',
  'frisse-druiven-white-wine:riesling': 'Goed.  Je begrijpt Riesling nu beter:  - strak   - mineraal   - zuurgedreven   - groot bewaarpotentieel',
  'frisse-druiven-white-wine:sauvignon-blanc': 'Goed.  Je herkent Sauvignon Blanc nu op:  - gras   - kruisbes   - citrus   - hoge zuren   - groene paprika    Belangrijk onderscheidend profiel in blindproeven.',
  'frisse-druiven-white-wine:verdejo': 'Goed.  Je beheerst nu de belangrijkste frisse witte druiven.  Volgende stap:  **Module 5 — Rijke witte druiven**',
  'gezondheid-beer-zero:alcoholvrij-in-sociale-context': 'Sterk.  Je begrijpt nu dat bier 0.0 niet alleen een product is, maar onderdeel van een bredere lifestyle-verandering.',
  'gezondheid-beer-zero:calorieen-vergelijken': 'Sterk.  Je begrijpt nu hoe calorieën en voedingswaarde elkaar beïnvloeden binnen bier 0.0.',
  'gezondheid-beer-zero:hydratatie': 'Goed.  Je begrijpt nu de rol van bier 0.0 binnen hydratatie en waarom context belangrijk blijft.',
  'gezondheid-beer-zero:sport-en-herstel': 'Goed.  Je begrijpt nu waarom bier 0.0 in sportcontext steeds vaker een rol speelt, maar ook waar de grenzen liggen.',
  'gezondheid-beer-zero:suiker-en-restsuiker': 'Goed gedaan.  Je begrijpt nu dat suiker een belangrijke nuance is binnen alcoholvrij bier.',
  'highballs-cocktails:dark-n-stormy': 'Goed. Je begrijpt nu hoe rum extra body en diepte toevoegt.',
  'highballs-cocktails:mojito': 'Perfect. Je begrijpt nu waarom techniek en frisheid cruciaal zijn in Mojito.',
  'highballs-cocktails:moscow-mule': 'Sterk. Je begrijpt nu de rol van ginger beer als krachtige modifier.',
  'highballs-cocktails:paloma': 'Perfect. Je begrijpt nu de belangrijkste highball- en longdrinkstructuren.',
  'highballs-cocktails:tom-collins': 'Goed. Je begrijpt nu hoe sourstructuur verlengd wordt naar highball.',
  'ingredienten-cocktails:base-spirits': 'Perfect. Je kunt nu de belangrijkste base spirits herkennen en hun rol in cocktails begrijpen.',
  'ingredienten-cocktails:bitters': 'Sterk. Je begrijpt nu waarom bitters in kleine hoeveelheden grote impact maken.',
  'ingredienten-cocktails:citrus-en-suikers': 'Perfect. Je begrijpt nu hoe zuur en zoet de kern vormen van cocktailbalans.',
  'ingredienten-cocktails:likeuren': 'Goed. Je begrijpt nu hoe likeuren complexiteit, zoetheid en diepte toevoegen.',
  'ingredienten-cocktails:mini-toets-cocktails': 'Perfect. Je hebt Explorer-niveau afgerond.',
  'intelligence-biodynamic:data-en-voorkeuren': 'Goed. Je begrijpt nu hoe data jouw drinkkeuzes slimmer maakt.',
  'intelligence-biodynamic:eigen-smaakprofiel': 'Sterk. Je begrijpt nu hoe jouw smaakprofiel ontstaat.',
  'intelligence-biodynamic:patronen-herkennen': 'Goed. Je begrijpt nu hoe patroonherkenning werkt.',
  'intelligence-biodynamic:persoonlijke-drinkintelligentie': 'Perfect. Je beheerst nu jouw persoonlijke tasting intelligence en bent klaar voor het eindassessment.',
  'intelligence-biodynamic:tasting-journal-gebruiken': 'Sterk. Je begrijpt nu waarom een tasting journal de basis is van tasting intelligence.',
  'intro-beer-zero:belangrijkste-categorieen': 'Goed gedaan.  Je herkent nu de belangrijkste bier 0.0-stijlen.  Dit vormt de basis voor de Specialist-module, waar je deze stijlen veel dieper gaat analyseren.',
  'intro-beer-zero:geschiedenis-van-alcoholvrij-bier': 'Goed.  Je begrijpt nu hoe alcoholvrij bier zich ontwikkeld heeft van nicheproduct naar volwassen wereldcategorie.  Dat historische perspectief helpt je de huidige markt beter te begrijpen.',
  'intro-beer-zero:hoe-wordt-alcohol-verwijderd': 'Goed gedaan.  Je begrijpt nu dat alcoholvrij bier op meerdere manieren gemaakt kan worden en dat elke techniek invloed heeft op smaak, body en aroma.  Dit inzicht helpt je later beter te begrijpen waarom sommige 0.0-bieren voller of frisser smaken dan andere.',
  'intro-beer-zero:waarom-is-bier-0-0-uniek': 'Sterk.  Je begrijpt nu dat bier 0.0 niet alleen een alternatief is voor alcohol, maar een zelfstandige categorie met eigen functionele en gastronomische waarde.  Dat maakt deze categorie relevanter dan ooit.',
  'intro-beer-zero:wat-is-bier-0-0': 'Goed. Je begrijpt nu de basis van bier 0.0.',
  'intro-beer:alcoholische-gisting': 'Sterk. Je begrijpt nu hoe gisting alcohol, koolzuur en aroma’s produceert.',
  'intro-beer:biercategorieen': 'Perfect. Je kent nu het fundament van bier.',
  'intro-beer:ondergisting-vs-bovengisting': 'Goed. Je kunt nu het verschil tussen de twee belangrijkste gistingsvormen uitleggen.',
  'intro-beer:vier-basisingredienten': 'Goed gedaan. Je begrijpt nu hoe de vier basisingrediënten samen bier vormen.',
  'intro-beer:wat-is-bier': 'Sterk begin. Je begrijpt nu wat bier in essentie is.',
  'intro-biodynamic:elementen-biodynamiek': 'Goed. Je begrijpt nu de energetische basisstructuur.',
  'intro-biodynamic:maria-thun-oorsprong': 'Sterk. Je begrijpt nu waar de biodynamische kalender vandaan komt.',
  'intro-biodynamic:vier-dagtypen': 'Perfect. Je kent nu de vier basisdagen.',
  'intro-biodynamic:waarom-gebruiken-professionals-dit': 'Perfect. Je begrijpt nu waarom biodynamische timing praktisch waardevol kan zijn.',
  'intro-biodynamic:wat-is-biodynamisch-proeven': 'Goed. Je begrijpt nu dat biodynamisch proeven draait om ritme, observatie en timing.',
  'intro-cocktails:basisstructuren-cocktails': 'Perfect. Je kunt nu de vier belangrijkste cocktailstructuren herkennen en analyseren.',
  'intro-cocktails:geschiedenis-van-cocktails': 'Goed. Je begrijpt nu hoe cocktails historisch zijn ontstaan en waarom klassieke structuren vandaag nog steeds leidend zijn.',
  'intro-cocktails:klassieke-cocktailcategorieen': 'Perfect. Je hebt nu de volledige cocktailbasis gelegd.',
  'intro-cocktails:spirit-modifier-balance': 'Sterk. Je begrijpt nu hoe cocktailbalans werkt en waarom structuur de basis vormt van iedere cocktail.',
  'intro-cocktails:wat-is-een-cocktail': 'Goed! Je begrijpt nu wat een cocktail is.',
  'intro-port:fortificatie': '### Goed gedaan Fortificatie is het fundament van Port. Zonder dit proces zou Port geen versterkte wijn zijn.  ### Wat je moet onthouden - Fortificatie stopt de vergisting vroegtijdig. - Hierdoor blijft natuurlijke druivensuiker behouden. - Aguardente verhoogt het alcoholpercentage.',
  'intro-port:geschiedenis-van-port': '### Goed gedaan De geschiedenis van Port verklaart waarom Engeland zo’n grote rol speelt in deze wijncategorie.  ### Wat je moet onthouden - Handelsconflicten stimuleerden Port-export. - Britse huizen bouwden de markt op. - De Douro werd vroeg beschermd.',
  'intro-port:portcategorieen': 'Goed! Je kent nu de basisstijlen van Port.',
  'intro-port:waarom-is-port-uniek': '### Goed gedaan Port onderscheidt zich door zijn combinatie van restsuiker, alcohol en rijpingsstijlen.  ### Wat je moet onthouden - Port is altijd versterkt. - Rijping bepaalt stijl en complexiteit. - De Douro is essentieel voor identiteit.',
  'intro-port:wat-is-port': 'Goed! Je kent nu de basis van Port.',
  'intro-red-wine:geschiedenis-rode-wijn': 'Goed gedaan.  Je begrijpt nu beter:  - hoe wijnbouw zich verspreidde - waarom Europa zo belangrijk werd - welke klassieke regio’s leidend zijn  Ga door naar de volgende les.',
  'intro-red-wine:hoe-ontstaat-rode-wijn': 'Goed gedaan.  Je begrijpt nu beter:  - hoe rode wijn ontstaat - waarom schilcontact belangrijk is - hoe extractie werkt  Ga door naar de volgende les.',
  'intro-red-wine:rode-wijncategorieen': 'Perfect. Je hebt nu de fundering van rode wijn gelegd.',
  'intro-red-wine:waarom-is-rode-wijn-uniek': 'Goed gedaan.  Je begrijpt nu beter:  - waarom tannines belangrijk zijn - waarom rode wijn bewaarpotentieel heeft - waarom pairing essentieel is  Ga door naar de volgende les.',
  'intro-red-wine:wat-is-rode-wijn': 'Sterk begin. Je begrijpt nu de basis van rode wijn.',
  'intro-rose-wine:belangrijkste-rosestijlen': 'Sterk. Je kent nu de fundamentele basis van rosé.',
  'intro-rose-wine:geschiedenis-van-rose': 'Goed.  De historische ontwikkeling van rosé is nu helder.  Belangrijk:  - rosé is één van de oudste stijlen - extractietechniek veranderde rode wijn - Provence werd de moderne standaard',
  'intro-rose-wine:hoe-ontstaat-rose': 'Goed. Je begrijpt nu hoe rosé technisch ontstaat.  Belangrijk:  - schilcontact bepaalt kleur - extractieduur bepaalt intensiteit - timing is cruciaal voor stijl',
  'intro-rose-wine:waarom-is-rose-uniek': 'Sterk.  Je begrijpt nu waarom rosé veel meer is dan een eenvoudige terraswijn.  Belangrijk:  - rosé heeft breed gastronomisch bereik - stijl bepaalt inzetbaarheid - rosé heeft unieke balans',
  'intro-rose-wine:wat-is-rose': 'Goed! Je begrijpt nu de basis van rosé.',
  'intro-sparkling:belangrijkste-categorieen': 'Goed! Je hebt nu de basis van mousserende wijn gelegd.',
  'intro-sparkling:geschiedenis-mousserende-wijn': 'Sterk.  Je begrijpt nu hoe mousserende wijn zich historisch heeft ontwikkeld.  Belangrijkste leerpunten:  - Bubbels waren vroeger ongewenst - Tweede gisting veranderde alles - Champagne werd het wereldreferentiepunt',
  'intro-sparkling:hoe-ontstaan-bubbels': 'Sterk.  Je begrijpt nu hoe koolzuur ontstaat en waarom autolyse belangrijk is.  Belangrijkste leerpunten:  - Gisting produceert CO2 - CO2 blijft gevangen in fles of tank - Autolyse verhoogt complexiteit',
  'intro-sparkling:waarom-is-mousserend-uniek': 'Goed.  Je begrijpt nu waarom mousserende wijn zo breed inzetbaar is.  Belangrijkste leerpunten:  - Zuur en mousse maken pairing krachtig - Textuur is uniek - Gastronomische inzetbaarheid is groot',
  'intro-sparkling:wat-is-mousserende-wijn': 'Goed gedaan.  Je begrijpt nu de absolute basis van mousserende wijn.  Belangrijkste leerpunten:  - Mousserende wijn bevat opgelost CO2 - Tweede gisting zorgt meestal voor bubbels - Mousse is een belangrijk kwaliteitskenmerk',
  'intro-white-wine:geschiedenis-witte-wijn': 'Goed.  Je kent nu de historische basis van witte wijn.  Belangrijk om te begrijpen:  - waar stijlen vandaan komen   - waarom regio’s zo belangrijk zijn   - hoe techniek kwaliteit heeft veranderd',
  'intro-white-wine:hoe-ontstaat-witte-wijn': 'Goed.  Je begrijpt nu:  - hoe witte wijn technisch ontstaat   - waarom temperatuur belangrijk is   - hoe productiekeuzes stijl beïnvloeden    Dit fundament is essentieel voor alle volgende modules.',
  'intro-white-wine:waarom-is-witte-wijn-uniek': 'Goed.  Je begrijpt nu waarom witte wijn zo breed inzetbaar is:  - fris   - rijk   - aromatisch   - gastronomisch    Dit maakt witte wijn één van de meest veelzijdige wijncategorieën.',
  'intro-white-wine:wat-is-witte-wijn': 'Goed.  Je begrijpt nu:  - wat witte wijn is   - waarom schilcontact belangrijk is   - waarom zuur zo’n grote rol speelt    Sterke basis voor de rest van de track.',
  'intro-white-wine:witte-wijncategorieen': 'Goed! Je begrijpt nu de basis van witte wijn.',
  'intro-wine:belangrijkste-wijncategorieen': 'Perfect. Je kent nu de fundamentele wereld van wijn.',
  'intro-wine:geschiedenis-van-wijn': 'Goed gedaan.  Je begrijpt nu hoe wijn zich historisch heeft ontwikkeld.  Belangrijkste leerpunten:  - wijn begon in Georgië - Grieken en Romeinen verspreidden wijncultuur - Europa vormde de moderne wijnwereld  Historische kennis helpt wijnregio’s beter begrijpen.',
  'intro-wine:hoe-ontstaat-wijn': 'Goed gedaan.  Je begrijpt nu hoe wijn ontstaat: van druif tot fermentatie en rijping.  Belangrijkste leerpunten:  - wijn start altijd in de wijngaard - fermentatie maakt alcohol mogelijk - rijping bepaalt stijl en complexiteit  Je bent klaar voor de volgende stap: wijncategorieën.',
  'intro-wine:wat-is-wijn': 'Goed! Je begrijpt nu wat wijn in essentie is.',
  'intro-wine:wijnstijlen-basis': 'Goed gedaan.  Je kent nu de drie fundamentele wijncategorieën.  Belangrijkste leerpunten:  - stille wijn bevat geen koolzuur - mousserende wijn bevat natuurlijke of toegevoegde bubbels - versterkte wijn bevat extra alcohol  Dit onderscheid is essentieel voor verdere specialisatie.',
  'kalender-biodynamic:bladdagen-uitgelegd': 'Sterk. Je begrijpt nu waarom Bladdagen anders aanvoelen.',
  'kalender-biodynamic:bloemdagen-uitgelegd': 'Perfect. Je begrijpt nu de rol van Bloemdagen.',
  'kalender-biodynamic:hoe-lees-je-de-kalender': 'Perfect. Je kunt nu zelfstandig de biodynamische kalender lezen.',
  'kalender-biodynamic:vruchtdagen-uitgelegd': 'Sterk. Je begrijpt nu waarom Vruchtdagen zo populair zijn.',
  'kalender-biodynamic:worteldagen-uitgelegd': 'Goed. Je begrijpt nu de aardse logica van Worteldagen.',
  'klassiek-cocktails:daiquiri': 'Perfect. Je kent nu de vijf belangrijkste klassieke cocktailstructuren.',
  'klassiek-cocktails:manhattan': 'Perfect. Je kunt nu Manhattan analyseren als balans tussen kracht en elegantie.',
  'klassiek-cocktails:martini': 'Goed. Je begrijpt nu waarom de Martini hét voorbeeld is van spirit-forward perfectie.',
  'klassiek-cocktails:negroni': 'Goed. Je begrijpt nu hoe bitterheid en equal-parts balans samenkomen.',
  'klassiek-cocktails:old-fashioned': 'Sterk. Je begrijpt nu de meest pure klassieke cocktailstructuur.',
  'klassieke-stijlen-beer-zero:alcoholvrije-blond': 'Goed.  Je begrijpt nu waarom blond een sterke brugstijl is binnen bier 0.0.',
  'klassieke-stijlen-beer-zero:alcoholvrije-donker': 'Sterk.  Je begrijpt nu waarom donkere bierstijlen vaak verrassend goed werken in alcoholvrije vorm.',
  'klassieke-stijlen-beer-zero:alcoholvrije-ipa': 'Sterk.  Je begrijpt nu waarom IPA één van de meest succesvolle bier 0.0-stijlen is.',
  'klassieke-stijlen-beer-zero:alcoholvrije-pils': 'Goed.  Je begrijpt nu waarom pils de puurste test is voor kwaliteit binnen bier 0.0.',
  'klassieke-stijlen-beer-zero:alcoholvrije-witbieren': 'Goed gedaan.  Je begrijpt nu waarom witbier één van de meest toegankelijke alcoholvrije stijlen is.',
  'klassieke-stijlen-beer:blond': 'Sterk. Je begrijpt nu waarom Blond meer complexiteit biedt dan pils.',
  'klassieke-stijlen-beer:bockbier': 'Sterk. Je beheerst nu de klassieke bierfundamenten.',
  'klassieke-stijlen-beer:pilsner': 'Goed gedaan. Je herkent nu de basisstructuur van Pilsner.',
  'klassieke-stijlen-beer:weizen': 'Goed. Je kunt nu Weizen herkennen aan gistkarakter en tarwe.',
  'klassieke-stijlen-beer:witbier': 'Sterk. Je begrijpt nu het verschil tussen Witbier en Weizen.',
  'klassieke-stijlen-rose-wine:nieuwe-wereld-rose': 'Sterk. Je herkent nu de klassieke stijlen en hun verschillen.',
  'klassieke-stijlen-rose-wine:provence-rose': 'Goed.  Je begrijpt nu waarom Provence de wereldwijde benchmark voor rosé is.  Belangrijk:  - bleek zalmroze - finesse en elegantie - frisse droge stijl',
  'klassieke-stijlen-rose-wine:rosado-spanje': 'Goed.  Je begrijpt nu de kern van Spaanse rosado.  Belangrijk:  - fruitgedreven stijl - Navarra als kerngebied - Garnacha en Tempranillo',
  'klassieke-stijlen-rose-wine:rosato-italie': 'Sterk.  Je begrijpt nu hoe breed de Italiaanse rosato-wereld is.  Belangrijk:  - grote regionale verschillen - Chiaretto vs Cerasuolo - terroir speelt grote rol',
  'klassieke-stijlen-rose-wine:tavel': 'Sterk.  Je begrijpt nu waarom Tavel één van de krachtigste roséstijlen is.  Belangrijk:  - extractie - body - kruidigheid - gastronomische inzetbaarheid',
  'klimaat-terroir-wine:bodemtypes': 'Goed gedaan.  Je begrijpt nu hoe bodem wijn beïnvloedt.  Belangrijkste leerpunten:  - kalk geeft vaak finesse en spanning - klei geeft kracht en body - zand geeft zachtheid en elegantie - leisteen geeft concentratie en mineraliteit  Bodem is een cruciaal onderdeel van terroir.',
  'klimaat-terroir-wine:gematigd-klimaat': 'Goed gedaan.  Je begrijpt nu waarom gematigd klimaat vaak de meeste balans geeft.  Belangrijkste leerpunten:  - druiven rijpen goed zonder te veel zuur te verliezen - balans tussen frisheid en rijpheid ontstaat makkelijker - veel klassieke regio’s liggen in gematigde zones  Dit klimaat levert vaak complete en harmonieuze wijnen.',
  'klimaat-terroir-wine:koel-klimaat': 'Goed gedaan.  Je begrijpt nu hoe koel klimaat wijn beïnvloedt.  Belangrijkste leerpunten:  - koel klimaat zorgt voor langzamere rijping - hogere zuren blijven beter behouden - wijnen worden vaak frisser, strakker en eleganter  Koele klimaten zijn essentieel voor precisie en finesse.',
  'klimaat-terroir-wine:terroir-uitgelegd': 'Perfect. Je begrijpt nu waarom plaats en omgeving wijn vormen.  Vanaf module 7 ga je naar service — de vertaalslag van kennis naar gastbeleving.',
  'klimaat-terroir-wine:warm-klimaat': 'Goed gedaan.  Je begrijpt nu wat warm klimaat doet met wijn.  Belangrijkste leerpunten:  - warm klimaat versnelt rijping - suiker en alcohol stijgen sneller - wijnen krijgen vaak meer body en rijp fruit  Warm klimaat geeft vaak krachtigere wijnstijlen.',
  'krachtige-druiven-red-wine:cabernet-sauvignon': 'Goed gedaan.  Je begrijpt nu beter:  - Cabernet-structuur - bewaarpotentieel - blendrol',
  'krachtige-druiven-red-wine:malbec': 'Goed gedaan.  Je begrijpt nu beter:  - Malbec-volheid - Argentijnse stijl - toegankelijkheid',
  'krachtige-druiven-red-wine:mourvedre': 'Goed gedaan.  Je begrijpt nu beter:  - Mourvèdre-karakter - GSM-blends - late rijping',
  'krachtige-druiven-red-wine:nebbiolo': 'Goed gedaan.  Je begrijpt nu beter:  - Nebbiolo-complexiteit - tanninestructuur - Barolo-herkenning',
  'krachtige-druiven-red-wine:syrah': 'Goed gedaan.  Je begrijpt nu beter:  - Syrah vs Shiraz - peperprofiel - klimaatinvloed',
  'lichte-druiven-red-wine:cinsault': 'Goed gedaan.  Je begrijpt nu beter:  - blendgebruik - soepelheid - rosé-link',
  'lichte-druiven-red-wine:gamay': 'Goed gedaan.  Je begrijpt nu beter:  - Gamay-stijl - fruitexpressie - carbonic maceration',
  'lichte-druiven-red-wine:grenache': 'Goed gedaan.  Je begrijpt nu beter:  - Grenache warmteprofiel - blends - alcoholbalans',
  'lichte-druiven-red-wine:mencia': 'Goed gedaan.  Je begrijpt nu beter:  - Spaanse finesse - mineraliteit - frisse structuur',
  'lichte-druiven-red-wine:pinot-noir': 'Goed gedaan.  Je begrijpt nu beter:  - elegantie in rode wijn - Pinot Noir herkenning - terroirgevoeligheid',
  'markt-innovatie-beer-zero:craft-0-0': 'Sterk.  Je begrijpt nu waarom craft-brouwers de innovatie-motor zijn van bier 0.0.',
  'markt-innovatie-beer-zero:functionele-bieren': 'Sterk.  Je begrijpt nu hoe bier 0.0 steeds meer richting lifestyle en functionaliteit beweegt.',
  'markt-innovatie-beer-zero:grote-merken': 'Goed.  Je begrijpt nu waarom grote merken cruciaal zijn in de groei en acceptatie van bier 0.0.',
  'markt-innovatie-beer-zero:isotone-positionering': 'Goed gedaan.  Je begrijpt nu dat marketingpositionering niet altijd gelijk staat aan functionele waarde.',
  'markt-innovatie-beer-zero:premium-alcoholvrij': 'Goed.  Je begrijpt nu hoe premium bier 0.0 zich ontwikkelt en waarom consumenten daarin meegroeien.',
  'medium-druiven-red-wine:barbera': 'Goed gedaan.  Je begrijpt nu beter:  - Barbera-zuren - drinkbaarheid - Piemonte-context',
  'medium-druiven-red-wine:merlot': 'Goed gedaan.  Je begrijpt nu beter:  - Merlot structuur - fruitprofiel - Bordeaux-context',
  'medium-druiven-red-wine:sangiovese': 'Goed gedaan.  Je begrijpt nu beter:  - zuurstructuur - Italiaanse stijl - foodpairing',
  'medium-druiven-red-wine:tempranillo': 'Goed gedaan.  Je begrijpt nu beter:  - Spaanse houtstijl - Tempranillo-profiel - Rioja-classificatie',
  'medium-druiven-red-wine:zinfandel': 'Goed gedaan.  Je begrijpt nu beter:  - Zinfandel-profiel - Primitivo-link - Californische stijl',
  'moderne-stijlen-beer:barleywine': 'Sterk. Je beheerst nu de belangrijkste moderne bierstijlen.',
  'moderne-stijlen-beer:ipa': 'Goed gedaan. Je begrijpt nu waarom IPA centraal staat in craft beer.',
  'moderne-stijlen-beer:neipa': 'Sterk. Je herkent nu het verschil tussen klassieke IPA en NEIPA.',
  'moderne-stijlen-beer:porter': 'Goed. Je begrijpt nu de zachtere roast-structuur van Porter.',
  'moderne-stijlen-beer:stout': 'Sterk. Je kunt nu Stout onderscheiden op roast, body en intensiteit.',
  'oorsprong-port:classificatie-douro': 'Goed! Je begrijpt nu hoe de Douro zijn wijngaarden beoordeelt en waarom classificatie een belangrijke sleutel is tot Portkwaliteit.',
  'oorsprong-port:douro-vallei': 'Goed! Je begrijpt nu hoe de Douro is opgebouwd en waarom deze regio de basis vormt van Portkwaliteit.',
  'oorsprong-port:druiven-van-port': 'Goed! Je kent nu de belangrijkste druiven van Port en begrijpt waarom blending zo essentieel is voor kwaliteit en stijl.',
  'oorsprong-port:klimaat-en-terroir': 'Goed! Je begrijpt nu hoe klimaat en terroir direct invloed hebben op de stijl, structuur en kwaliteit van Port.',
  'oorsprong-port:waar-komt-port-vandaan': 'Goed! Je begrijpt nu waar Port vandaan komt en waarom de Douro de basis vormt van alles wat Port uniek maakt.',
  'pairing-beer-zero:0-0-en-kaas': 'Sterk.  Je begrijpt nu waarom kaas één van de beste leermiddelen is voor bierpairing.',
  'pairing-beer-zero:0-0-en-lichte-gerechten': 'Goed gedaan.  Je begrijpt nu hoe lichte gerechten vragen om precisie en subtiliteit.',
  'pairing-beer-zero:0-0-en-lunch': 'Goed.  Je begrijpt nu waarom bier 0.0 perfect past binnen lichte lunchpairings.',
  'pairing-beer-zero:bier-0-0-in-gastronomie': 'Gefeliciteerd.  Je begrijpt nu hoe bier 0.0 een serieuze rol speelt binnen moderne gastronomie en pairing.',
  'pairing-beer-zero:contrast-en-harmonie': 'Sterk.  Je begrijpt nu de twee fundamenten van professionele pairing.',
  'pairing-beer:bier-en-desserts': 'Sterk. Je begrijpt nu hoe bier gastronomisch breed inzetbaar is.',
  'pairing-beer:bier-en-kaas': 'Sterk. Je begrijpt nu waarom bier en kaas zo krachtig kunnen combineren.',
  'pairing-beer:bier-en-vlees': 'Goed gedaan. Je kunt nu bier afstemmen op vleesstructuur en grill.',
  'pairing-cocktails:aperol-spritz': 'Sterk. Je kunt nu spirits beter blind herkennen op aroma en structuur.',
  'pairing-cocktails:cocktails-als-aperitief': 'Goed. Je begrijpt nu waarom bitter, fris en droog ideaal zijn vóór de maaltijd.',
  'pairing-cocktails:cocktails-als-digestief': 'Perfect. Je begrijpt nu hoe cocktails gastronomisch kunnen worden ingezet.',
  'pairing-cocktails:cocktails-bij-foodpairing': 'Perfect. Je begrijpt nu hoe cocktailstructuur gekoppeld wordt aan gerechten.',
  'pairing-red-wine:rode-wijn-kaas': 'Goed gedaan.  Je begrijpt nu beter:  - kaasstructuur - zoutinvloed - intensiteitsmatching',
  'pairing-red-wine:rode-wijn-vlees': 'Goed gedaan.  Je begrijpt nu beter:  - eiwit-tannine interactie - vetbalans - klassieke vleespairings',
  'pairing-red-wine:rode-wijn-wild': 'Goed gedaan.  Je begrijpt nu beter:  - wildpairings - sausinvloed - tertiaire complexiteit - klassieke combinaties ```',
  'pairing-rose-wine:rose-en-aziatisch': 'Sterk.  Je begrijpt nu hoe rosé spice en umami kan balanceren.  Belangrijk:  - fruit ondersteunt spice - zuur houdt spanning - zachte structuur helpt balans',
  'pairing-rose-wine:rose-en-barbecue': 'Goed.  Je begrijpt nu waarom rosé barbecue technisch sterk ondersteunt.  Belangrijk:  - vet + zuur - rook + fruit - body + kruiden',
  'pairing-rose-wine:rose-en-charcuterie': 'Goed.  Je begrijpt nu waarom rosé een onderschatte charcuterie-wijn is.  Belangrijk:  - zout en vet vragen frisheid - fruit houdt spanning - structuur maakt pairing compleet',
  'pairing-rose-wine:rose-en-fine-dining': 'Uitstekend. Je beheerst nu rosépairing op hoog niveau.',
  'pairing-rose-wine:rose-en-salades': 'Goed.  Je begrijpt nu waarom rosé uitstekend werkt met salades.  Belangrijk:  - zuren matchen dressing - frisheid houdt balans - lichte body voorkomt dominantie',
  'pairing-rose-wine:rose-en-vis': 'Sterk.  Je begrijpt nu waarom rosé één van de beste viswijnen kan zijn.  Belangrijk:  - vet bepaalt bodykeuze - frisheid ondersteunt vis - structuur maakt rosé flexibel',
  'pairing-sparkling:mousserend-als-maaltijdwijn': 'Uitstekend. Je begrijpt nu waarom mousserende wijn één van de meest gastronomische wijnstijlen ter wereld is.',
  'pairing-sparkling:mousserend-en-kaas': 'Sterk.  Je begrijpt nu hoe vet, zout en rijping in kaas samenwerken met mousserende wijn.  Belangrijkste leerpunten:  - Vet vraagt zuur - Intensiteit moet kloppen - Zoete stijlen kunnen verrassend sterk zijn',
  'pairing-sparkling:mousserend-en-oesters': 'Goed gedaan.  Je begrijpt nu waarom oesters en mousserende wijn één van de meest klassieke pairings zijn.  Belangrijkste leerpunten:  - Zilt vraagt frisheid - Mousse reinigt het gehemelte - Droge stijlen werken meestal het best',
  'pairing-white-wine:witte-wijn-gevogelte': 'Goed.  Je begrijpt nu de basis van gastronomische witte wijnpairing.  Volgende stap:  **Module 9 — Blindproeven & Examen**',
  'pairing-white-wine:witte-wijn-kaas': 'Goed.  Je begrijpt nu:  - waarom zuur en vet perfect samenwerken   - waarom wit vaak beter werkt dan rood   - hoe kaasstijl pairing beïnvloedt',
  'pairing-white-wine:witte-wijn-vis': 'Goed.  Je begrijpt nu:  - waarom zuur essentieel is bij vis   - hoe vet en frisheid samenwerken   - waarom intensiteit matchen belangrijk is   - waarom tannine vaak botst met vis    Vispairing is één van de belangrijkste fundamenten van wijn-spijs.',
  'pairing-wine:wijn-en-kaas': 'Goed gedaan.  Je begrijpt nu hoe wijn en kaas elkaar beïnvloeden.  Belangrijkste leerpunten:  - zout verzacht tannines - vet maakt wijn zachter en ronder - intensiteit tussen wijn en kaas moet in balans zijn  Kaaspairing draait om textuur, zout en harmonie.',
  'pairing-wine:wijn-en-vis': 'Goed gedaan.  Je begrijpt nu hoe wijn met vis werkt.  Belangrijkste leerpunten:  - vis vraagt meestal om frisheid en precisie - vettere vis kan meer body aan - saus bepaalt vaak sterker de pairing dan de vis zelf  Vispairing draait sterk om zuur en textuur.',
  'pairing-wine:wijn-en-vlees': 'Perfect. Je begrijpt nu de basis van gastronomisch wijninzicht.  Je bent klaar voor de laatste module: blindproeven en het afsluitende examen.',
  'port-premium:colheita-port': 'Goed! Je begrijpt nu waarom Colheita een unieke brug vormt tussen Tawny en Vintage.',
  'port-premium:garrafeira-port': 'Goed! Je begrijpt nu waarom Garrafeira één van de meest unieke en mysterieuze Portstijlen is.',
  'portstijlen-verdiept:crusted-port': 'Goed! Je begrijpt nu waarom Crusted Port een verborgen parel is binnen de Portwereld.',
  'portstijlen-verdiept:single-quinta-vintage-port': 'Goed! Je begrijpt nu waarom Single Quinta Vintage Port zo interessant is voor liefhebbers en kenners.',
  'portstijlen-verdiept:tawny-met-leeftijd': 'Goed! Je begrijpt nu waarom Aged Tawny één van de meest verfijnde en complexe Portcategorieën is.',
  'portstijlen-verdiept:vintage-port-deel-1': 'Goed! Je begrijpt nu waarom Vintage Port als de meest prestigieuze Portstijl wordt gezien.',
  'portstijlen-verdiept:vintage-port-deel-2': 'Goed! Je begrijpt nu waarom Vintage Port één van de grootste bewaarwijnen ter wereld is.',
  'portstijlen:crusted-port': 'Goed! Je begrijpt nu waarom Crusted Port een verborgen parel is binnen de Portwereld.',
  'portstijlen:late-bottled-vintage': 'Goed! Je begrijpt nu waarom LBV een belangrijke stijl is tussen Ruby en Vintage in.',
  'portstijlen:rose-port': 'Goed! Je begrijpt nu waarom Rosé Port een moderne en toegankelijke stijl is binnen de Portwereld.',
  'portstijlen:ruby-port': 'Goed! Je begrijpt nu waarom Ruby Port de meest fruitige en toegankelijke stijl is.',
  'portstijlen:tawny-port': 'Goed! Je begrijpt nu waarom Tawny Port zachter, rijper en complexer is dan Ruby.',
  'portstijlen:white-port': 'Goed! Je begrijpt nu waarom White Port een unieke en veelzijdige stijl binnen Port is.',
  'praktijk-port:port-en-desserts': 'Sterk. Je begrijpt nu hoe Port en desserts elkaar kunnen versterken en waarom detail in zoetheidsbalans cruciaal is.',
  'praktijk-port:port-en-kaas': 'Sterk. Je begrijpt nu waarom Port en kaas één van de krachtigste gastronomische combinaties zijn.',
  'praktijk-port:port-in-gastronomie': 'Uitstekend. Je begrijpt nu dat Port in gastronomie veel breder inzetbaar is dan alleen na het dessert.',
  'praktijk-port:port-serveren': 'Sterk. Je beheerst nu één van de meest onderschatte onderdelen van Port: correcte service. Dit onderscheidt een liefhebber van een specialist.',
  'productie-beer-zero:aroma-retentie': 'Goed gedaan.  Je begrijpt nu dat aroma vaak de grootste uitdaging is in bier 0.0.  Behoud van geur bepaalt sterk hoe “echt” een bier aanvoelt.',
  'productie-beer-zero:balans-zonder-alcohol': 'Sterk.  Je begrijpt nu waarom balans de moeilijkste technische uitdaging is binnen bier 0.0.  Vanaf nu kun je productiemethoden koppelen aan smaakresultaten.',
  'productie-beer-zero:gestopte-fermentatie': 'Goed gedaan.  Je begrijpt nu dat gestopte fermentatie technisch eenvoudig is, maar vaak invloed heeft op restsuiker en zoetheid.  Dit helpt je later beter verklaren waarom sommige 0.0-bieren zoeter smaken.',
  'productie-beer-zero:reverse-osmosis': 'Sterk.  Je begrijpt nu dat reverse osmosis technisch zeer geavanceerd is en veel controle geeft over smaakbehoud.  Dit maakt het één van de meest precieze productiemethoden.',
  'productie-beer-zero:vacuümdestillatie': 'Goed.  Je begrijpt nu waarom vacuümdestillatie één van de meest gebruikte premium-technieken is voor bier 0.0.  Het behoud van aroma maakt hier vaak het verschil.',
  'productie-beer:gist-en-aroma': 'Sterk. Je begrijpt nu waarom gist zo belangrijk is voor bierstijl.',
  'productie-beer:hop-en-bitterheid': 'Goed. Je begrijpt nu hoe hop bitterheid en aroma opbouwt.',
  'productie-beer:lagering-en-rijping': 'Perfect. Je begrijpt nu het volledige brouwfundament.',
  'productie-beer:maischen': 'Sterk. Je begrijpt nu hoe suikers vrijkomen tijdens het brouwen.',
  'productie-beer:mouten-uitgelegd': 'Goed gedaan. Je begrijpt nu hoe mout kleur, body en alcohol beïnvloedt.',
  'productie-port:douro-vallei': 'Goed! Je begrijpt nu waarom de Douro uniek is.',
  'productie-port:druiven-van-port': 'Goed! Je begrijpt nu waarom druivenkeuze zo belangrijk is.',
  'productie-port:houtlagering': 'Goed! Je begrijpt nu houtlagering.',
  'productie-port:klimaat-en-terroir': 'Goed! Je begrijpt nu hoe terroir werkt.',
  'productie-port:oxidatie-uitgelegd': 'Goed! Je begrijpt nu waarom oxidatie belangrijk is in Port.',
  'productie-red-wine:alcoholische-gisting': 'Goed gedaan.  Je begrijpt nu beter:  - hoe alcohol ontstaat - hoe gist werkt - waarom temperatuur belangrijk is  Ga door naar de volgende les.',
  'productie-red-wine:extractie-kleur-tannine': 'Goed gedaan.  Je begrijpt nu beter:  - wat extractie betekent - hoe extractie kracht beïnvloedt - waarom balans cruciaal is  Ga door naar de volgende les.',
  'productie-red-wine:houtlagering': 'Goed gedaan.  Je begrijpt nu beter:  - wat hout doet - hoe eiken invloed geeft - waarom zuurstof belangrijk is  Ga door naar de volgende les.',
  'productie-red-wine:rijping-rode-wijn': 'Perfect. Je begrijpt nu hoe rode wijn wordt gemaakt en ontwikkelt.',
  'productie-red-wine:schilcontact-uitgelegd': 'Goed gedaan.  Je begrijpt nu beter:  - hoe schilcontact werkt - hoe kleur ontstaat - hoe tannines worden opgebouwd  Ga door naar de volgende les.',
  'productie-rose-wine:direct-press-methode': 'Goed.  Je begrijpt nu waarom direct press de standaard is voor lichte premium rosé.  Belangrijk:  - zeer kort schilcontact - minimale extractie - maximale finesse',
  'productie-rose-wine:fermentatie-van-rose': 'Sterk.  Fermentatie is één van de belangrijkste stijlbepalers van rosé.  Belangrijk:  - temperatuurcontrole - aromabehoud - reductieve wijnmaakstijl',
  'productie-rose-wine:frisse-vs-gastronomische-rose': 'Perfect. Je begrijpt nu de productiebasis van rosé.',
  'productie-rose-wine:kleurcontrole': 'Goed.  Je begrijpt nu hoe wijnmakers kleur sturen.  Belangrijk:  - extractietijd - druivenras - persdruk',
  'productie-rose-wine:saignee-methode': 'Sterk.  Je begrijpt nu dat saignée zowel rosé als rode wijn beïnvloedt.  Belangrijk:  - diepere extractie - meer body - krachtigere stijl',
  'productie-sparkling:charmat-tankmethode': 'Goed.  Je begrijpt nu waarom de tankmethode vooral draait om frisheid en fruitexpressie.  Belangrijkste leerpunten:  - Tweede gisting in tank - Minder autolyse - Ideaal voor fruitgedreven stijlen',
  'productie-sparkling:dosage-uitgelegd': 'Goed! Je begrijpt nu hoe productiemethode en dosage de stijl van mousserende wijn bepalen.',
  'productie-sparkling:methode-ancestrale': 'Sterk.  Je begrijpt nu de meest pure en spontane mousserende productiemethode.  Belangrijkste leerpunten:  - Eén gisting - Vroege botteling - Vaak ongefilterd',
  'productie-sparkling:methode-traditionnelle': 'Goed gedaan.  Je begrijpt nu hoe de traditionele methode werkt en waarom dit de kwaliteitsstandaard is voor mousserende wijn.  Belangrijkste leerpunten:  - Tweede gisting vindt plaats op fles - Autolyse zorgt voor complexiteit - Dégorgement is essentieel voor helderheid',
  'productie-sparkling:transfermethode': 'Goed.  Je begrijpt nu hoe transfer een hybride methode is.  Belangrijkste leerpunten:  - Start op fles - Eindigt in tank - Meer efficiënt dan traditioneel',
  'productie-white-wine:alcoholische-gisting': 'Goed.  Je begrijpt nu:  - hoe alcohol ontstaat   - waarom temperatuur cruciaal is   - hoe fermentatie aroma’s beïnvloedt',
  'productie-white-wine:direct-press': 'Goed.  Je begrijpt nu:  - waarom direct press zo belangrijk is   - hoe schilcontact stijl beïnvloedt   - waarom frisheid behouden blijft    Dit is de basis van moderne witte wijnproductie.',
  'productie-white-wine:malolactische-gisting': 'Goed.  Je begrijpt nu:  - hoe MLF werkt   - waarom het wijn zachter maakt   - waarom Chardonnay vaak romiger smaakt',
  'productie-white-wine:rijping-witte-wijn': 'Goed! Je begrijpt nu hoe witte wijn technisch wordt gevormd.',
  'productie-white-wine:rvs-vs-hout': 'Goed.  Je begrijpt nu:  - RVS versus hout   - stijlverschillen   - hoe rijping structuur beïnvloedt',
  'productie-wine:alcoholische-gisting': 'Goed gedaan.  Je begrijpt nu hoe alcohol in wijn ontstaat.  Belangrijkste leerpunten:  - gist zet suiker om in alcohol - temperatuur beïnvloedt stijl en aroma - gisting is de kern van wijnproductie  Zonder fermentatie bestaat wijn niet.',
  'productie-wine:houtlagering': 'Goed gedaan.  Je begrijpt nu wat hout doet met wijn.  Belangrijkste leerpunten:  - hout geeft extra aroma’s zoals vanille en toast - hout verzacht tannines en voegt structuur toe - nieuw en oud hout geven verschillende effecten  Houtgebruik is een bewuste stijlkeuze.',
  'productie-wine:oxidatie-vs-reductie': 'Goed gedaan.  Je begrijpt nu het verschil tussen oxidatieve en reductieve wijnmaking.  Belangrijkste leerpunten:  - oxidatie geeft rijpere en notige aroma’s - reductie bewaart frisheid en fruit - zuurstofmanagement bepaalt stijl sterk  Dit concept is essentieel voor stijlherkenning.',
  'productie-wine:rijping-en-ontwikkeling': 'Perfect. Je begrijpt nu hoe wijn technisch wordt opgebouwd.',
  'productie-wine:van-druif-naar-wijn': 'Goed gedaan.  Je begrijpt nu de volledige basisflow van wijnproductie.  Belangrijkste leerpunten:  - wijnproductie start altijd met de oogst - persen levert most op als basis voor fermentatie - rijping bepaalt mede kwaliteit en stijl  Dit proces vormt de technische basis van alle wijn.',
  'proeven-beer-zero:bitterheid-en-balans': 'Goed gedaan.  Je begrijpt nu hoe bitterheid gebruikt wordt om balans te creëren.  Dat is cruciaal in bier 0.0.',
  'proeven-beer-zero:body-analyseren': 'Goed.  Je begrijpt nu waarom body één van de belangrijkste beoordelingspunten is bij bier 0.0.  Body bepaalt vaak hoe compleet een bier aanvoelt.',
  'proeven-beer-zero:hoe-proef-je-bier-0-0': 'Goed gedaan.  Je begrijpt nu dat bier 0.0 op dezelfde professionele manier geanalyseerd wordt als regulier bier.  De structuur kijken, ruiken en proeven vormt de basis voor alles wat volgt.',
  'proeven-beer-zero:mini-toets-0-0': 'Gefeliciteerd.  Je hebt nu de volledige Explorer-basis van Bier 0.0 afgerond.  Je kunt nu smaak analyseren, productiemethoden koppelen aan resultaten en stijlen herkennen.  Je bent klaar voor Specialist.',
  'proeven-beer-zero:zoetheid-herkennen': 'Sterk.  Je begrijpt nu dat zoetheid zowel positief als negatief kan werken.  Balans is belangrijker dan intensiteit.',
  'proeven-beer:aromas-herkennen': 'Goed. Je ontwikkelt nu actief je aromageheugen.',
  'proeven-beer:hoe-proef-je-bier': 'Goed gedaan. Je kunt nu bier systematisch analyseren.',
  'proeven-beer:mini-toets-bier': 'Sterk gedaan. Je hebt nu het volledige Explorer-fundament van bier afgerond.',
  'proeven-beer:schuim-analyseren': 'Sterk. Je begrijpt nu waarom schuim belangrijk is voor kwaliteit en presentatie.',
  'proeven-beer:structuur-en-mondgevoel': 'Sterk. Je kunt nu body, koolzuur en textuur beter herkennen.',
  'proeven-biodynamic:eerste-proefexperiment': 'Perfect. Je begrijpt nu hoe verschillende dagtypes de proefervaring kunnen beïnvloeden en hoe je dit systematisch analyseert.',
  'proeven-biodynamic:wijn-op-bladdag': 'Sterk. Je begrijpt nu hoe Bladdagen groenere tonen kunnen accentueren.',
  'proeven-biodynamic:wijn-op-bloemdag': 'Perfect. Je begrijpt nu de finesse-logica van Bloemdagen.',
  'proeven-biodynamic:wijn-op-vruchtdag': 'Sterk. Je begrijpt nu waarom Vruchtdagen zo geliefd zijn.',
  'proeven-biodynamic:wijn-op-worteldag': 'Goed. Je begrijpt nu hoe Worteldagen structuur blootleggen.',
  'proeven-port:aromas-herkennen': 'Goed! Je begrijpt nu hoe aroma’s ontstaan en hoe je ze gebruikt om Portstijlen beter te herkennen.',
  'proeven-port:mini-toets-port-proeven': 'Goed! Je hebt Module 3 afgerond. Je beschikt nu over de basisvaardigheden om Port professioneel te proeven en analyseren.',
  'proeven-port:proefnotitie-port': 'Goed! Je hebt nu geleerd hoe je Port systematisch kunt analyseren. Dit is de basis voor alle verdere proeftraining.',
  'proeven-port:ruby-vs-tawny-blind': 'Goed! Je kunt nu de belangrijkste verschillen tussen Ruby en Tawny herkennen. Dit is een belangrijke stap richting blindproeven.',
  'proeven-port:structuur-herkennen': 'Goed! Je begrijpt nu dat structuur minstens zo belangrijk is als aroma. Dit helpt je om Port objectiever te analyseren.',
  'proeven-red-wine:aromas-herkennen': 'Goed gedaan.  Je begrijpt nu beter:  - primair aroma - secundair aroma - tertiair aroma  Ga door naar de volgende les.',
  'proeven-red-wine:hoe-proef-je-rode-wijn': 'Goed gedaan.  Je begrijpt nu beter:  - systematisch proeven - observatie opbouwen - structuur herkennen  Ga door naar de volgende les.',
  'proeven-red-wine:kleur-analyseren': 'Goed gedaan.  Je begrijpt nu beter:  - hoe kleur leeftijd toont - hoe intensiteit druif verraadt - waarom randanalyse belangrijk is  Ga door naar de volgende les.',
  'proeven-red-wine:mini-toets-rode-wijn': 'Sterk gewerkt.  Je beheerst nu:  - basisproeven - kleuranalyse - aroma-herkenning - tannine-inschatting  Je bent klaar voor Specialist-niveau.',
  'proeven-red-wine:tannines-herkennen': 'Goed gedaan.  Je begrijpt nu beter:  - hoe tannines voelen - hoe structuur werkt - waarom tannines rijping dragen  Ga door naar de volgende les.',
  'proeven-rose-wine:aromas-herkennen': 'Goed.  Je herkent nu de belangrijkste aromagroepen in rosé.  Belangrijk:  - rood fruit - citrus - bloemen - kruiden',
  'proeven-rose-wine:hoe-proef-je-rose': 'Goed.  Je beheerst nu de vaste proefstructuur van rosé.  Belangrijk:  - systematisch proeven - eerst visueel analyseren - daarna geur en structuur beoordelen',
  'proeven-rose-wine:kleur-analyseren': 'Sterk.  Je begrijpt nu hoe kleur helpt bij stijlherkenning.  Belangrijk:  - kleurintensiteit - extractieduur - stijlindicatie',
  'proeven-rose-wine:mini-toets-rose': 'Sterk. Je hebt nu een solide basis in roséproeven.',
  'proeven-rose-wine:structuur-herkennen': 'Sterk.  Je begrijpt nu hoe structuur het verschil maakt in roséanalyse.  Belangrijk:  - zuur - body - alcohol - textuur',
  'proeven-sparkling:aromas-herkennen': 'Sterk.  Je begrijpt nu hoe primaire, secundaire en tertiaire aroma’s samenwerken.  Belangrijkste leerpunten:  - Primair = fruit - Secundair = autolyse - Tertiair = rijping',
  'proeven-sparkling:hoe-proef-je-mousserend': 'Goed gedaan.  Je begrijpt nu hoe een professionele proefanalyse van mousserende wijn is opgebouwd.  Belangrijkste leerpunten:  - Eerst kijken, dan ruiken, dan proeven - Mousse is een extra analysetool - Balans bepaalt kwaliteit',
  'proeven-sparkling:mini-toets-explorer': 'Uitstekend.  Je hebt de Explorer-fase succesvol afgerond.  Belangrijkste leerpunten:  - Je kunt mousse analyseren - Je herkent aromalagen - Je begrijpt structuur en balans  NOTE: Geen MC-quiz toevoegen. Deze les blijft bewust praktijkgericht als mini-toets.  # MOUS_MODULE_04_REPAIR.md  # Repair — Module 4 Champagne Doel: ontbrekende quizblokken en quiz-feedback herstellen.',
  'proeven-sparkling:mousse-analyseren': 'Goed.  Je kunt nu mousse gebruiken als kwaliteitsindicator.  Belangrijkste leerpunten:  - Kleine bubbels zijn vaak verfijnder - Persistentie is belangrijk - Mousse beïnvloedt textuur',
  'proeven-sparkling:structuur-herkennen': 'Goed.  Je begrijpt nu hoe structuur de kwaliteit van mousserende wijn helpt bepalen.  Belangrijkste leerpunten:  - Zuur geeft spanning - Dosage verzacht - Lengte is vaak een kwaliteitsindicator',
  'proeven-white-wine:aromas-herkennen': 'Goed.  Je kunt aroma’s nu indelen in:  - primair   - secundair   - tertiair    Dat maakt je proefanalyse veel sterker.',
  'proeven-white-wine:hoe-proef-je-witte-wijn': 'Goed.  Je beheerst nu de basisstructuur van professioneel proeven:  - kijken   - ruiken   - proeven   - analyseren    Dit vormt de basis van alle blindproeverijen.',
  'proeven-white-wine:kleur-analyseren': 'Goed.  Je begrijpt nu hoe kleur een eerste indicatie geeft van stijl en leeftijd.',
  'proeven-white-wine:mini-toets-witte-wijn': 'Goed gedaan.  Je hebt nu het volledige Explorer-fundament van witte wijn afgerond.  Volgende stap:  **Module 4 — Frisse witte druiven**',
  'proeven-white-wine:zuur-herkennen': 'Goed.  Je begrijpt nu hoe belangrijk zuur is voor kwaliteit, frisheid en bewaarpotentieel.',
  'proeven-wine:aromas-herkennen': 'Goed gedaan.  Je kunt nu aroma’s beter structureren.  Belangrijkste leerpunten:  - primair komt uit de druif - secundair komt uit productie - tertiair komt uit rijping  Aromalogica versnelt blindproeven.',
  'proeven-wine:hoe-proef-je-wijn': 'Goed gedaan.  Je begrijpt nu de vier vaste stappen van professioneel wijnproeven.  Belangrijkste leerpunten:  - wijnproeven is een gestructureerd proces - kijken, ruiken, proeven en concluderen vormen de basis - structuur is vaak belangrijker dan alleen smaak  Dit is de fundering van elke sommelier.',
  'proeven-wine:kleur-analyseren': 'Goed gedaan.  Je begrijpt nu hoe kleur informatie geeft over wijn.  Belangrijkste leerpunten:  - kleur zegt iets over leeftijd - kleur zegt iets over druif - kleur zegt iets over stijl  Visuele analyse is altijd de eerste stap.',
  'proeven-wine:mini-toets-wijn': 'Gefeliciteerd.  Je hebt nu de Explorer-basis van wijn gelegd.  Vanaf module 4 ga je veel dieper in op structuur, druivenrassen en terroir.',
  'proeven-wine:structuur-herkennen': 'Goed gedaan.  Je begrijpt nu de structurele bouwstenen van wijn.  Belangrijkste leerpunten:  - zuur geeft frisheid - tannine geeft grip - body en afdronk helpen kwaliteit bepalen  Structuur is de ruggengraat van analyse.',
  'rijke-druiven-white-wine:chardonnay': 'Goed.  Je herkent Chardonnay nu op:  - veelzijdigheid   - houtinvloed   - malolactische gisting   - boterigheid   - terroir-invloed    Chardonnay is één van de belangrijkste benchmark-druiven.',
  'rijke-druiven-white-wine:chenin-blanc': 'Goed.  Je begrijpt Chenin nu op:  - veelzijdigheid   - hoge zuren   - rijpingscapaciteit   - breed stijlbereik',
  'rijke-druiven-white-wine:marsanne-roussanne': 'Goed.  Je beheerst nu de belangrijkste rijke witte druiven.  Volgende stap:  **Module 6 — Aromatische witte druiven**',
  'rijke-druiven-white-wine:semillon': 'Goed.  Je begrijpt Semillon nu op:  - subtiele kracht   - structuur   - rijping   - blendfunctie   - edelzoete toepassingen',
  'rijke-druiven-white-wine:viognier': 'Goed.  Je herkent Viognier nu op:  - aromatische rijkdom   - volle body   - zachte textuur   - florale kracht',
  'service-beer-zero:bewaren': 'Goed.  Je begrijpt nu waarom opslag en versheid direct invloed hebben op kwaliteit.',
  'service-beer-zero:glaswerk': 'Sterk.  Je begrijpt nu waarom glaswerk een essentieel onderdeel is van professionele service.',
  'service-beer-zero:presentatie': 'Goed gedaan.  Je begrijpt nu dat presentatie niet decoratief is, maar onderdeel van kwaliteitsperceptie.',
  'service-beer-zero:serveertemperatuur': 'Goed.  Je begrijpt nu hoe temperatuur direct invloed heeft op smaak, frisheid en perceptie.',
  'service-beer-zero:service-in-de-praktijk': 'Sterk.  Je beheerst nu de volledige servicebasis van bier 0.0 op Master-niveau.  Dit vormt de brug naar pairing en gastronomie.',
  'service-beer:bewaren-en-rijping': 'Sterk. Je beheerst nu professionele bier-service.',
  'service-beer:glaswerk': 'Sterk. Je weet nu hoe glaswerk aroma en schuim beïnvloedt.',
  'service-beer:schenktechniek': 'Goed. Je begrijpt nu hoe correct schenken kwaliteit verhoogt.',
  'service-beer:serveertemperatuur': 'Goed gedaan. Je begrijpt nu hoe temperatuur smaakbeleving beïnvloedt.',
  'service-cocktails:garnishes': 'Sterk. Je begrijpt nu dat garnishes functioneel onderdeel zijn van de cocktail.',
  'service-cocktails:glaswerk': 'Perfect. Je begrijpt nu hoe glaswerk aroma, presentatie en beleving beïnvloedt.',
  'service-cocktails:ijsgebruik': 'Goed. Je begrijpt nu hoe ijs direct invloed heeft op balans en textuur.',
  'service-cocktails:serveertechniek': 'Perfect. Je beheerst nu de servicekant van cocktails op Master-niveau.',
  'service-red-wine:bewaren-en-kelderen': 'Goed gedaan.  Je begrijpt nu beter:  - opslagcondities - bewaarpotentieel - risico’s van warmte en licht',
  'service-red-wine:decanteren': 'Goed gedaan.  Je begrijpt nu beter:  - waarom je decanteert - jong vs oud verschil - timing en zuurstof',
  'service-red-wine:glaswerk-rode-wijn': 'Goed gedaan.  Je begrijpt nu beter:  - invloed van glasvorm - geurconcentratie - optimale wijnexpressie',
  'service-red-wine:serveertemperatuur-rode-wijn': 'Goed gedaan.  Je begrijpt nu beter:  - temperatuurinvloed op smaak - ideale serveerzones - balans tussen alcohol en structuur',
  'service-rose-wine:bewaren': 'Goed.  Je begrijpt nu hoe opslagkwaliteit direct invloed heeft op rosé.  Belangrijk:  - koel bewaren - donker bewaren - jong drinken is meestal ideaal',
  'service-rose-wine:glaswerk': 'Sterk.  Je begrijpt nu hoe glaswerk rosé kan versterken of beperken.  Belangrijk:  - glasvorm stuurt geur - volume beïnvloedt expressie - stijl bepaalt glaskeuze',
  'service-rose-wine:jong-drinken-vs-rijping': 'Sterk. Je beheerst nu de serviceprincipes van rosé op professioneel niveau.',
  'service-rose-wine:serveertemperatuur': 'Goed.  Je begrijpt nu hoe temperatuur directe invloed heeft op rosé.  Belangrijk:  - te koud sluit aroma’s - te warm vergroot alcoholgevoel - stijl bepaalt ideale temperatuur',
  'service-sparkling:bewaren-en-rijping': 'Sterk. Je beheerst nu de servicebasis van mousserende wijn op professioneel niveau.',
  'service-sparkling:glaswerk': 'Sterk.  Je begrijpt nu waarom glaswerk een groot verschil maakt.  Belangrijkste leerpunten:  - Flute is visueel sterk - Witwijnglas is aromatisch beter - Coupe is vooral decoratief',
  'service-sparkling:openen-zonder-verlies': 'Goed.  Je beheerst nu de professionele techniek om mousserende wijn veilig en kwaliteitsgericht te openen.  Belangrijkste leerpunten:  - Altijd de fles draaien - Kurk onder controle houden - Drukverlies minimaliseren',
  'service-sparkling:serveertemperatuur': 'Goed gedaan.  Je begrijpt nu hoe temperatuur direct invloed heeft op kwaliteit en beleving.  Belangrijkste leerpunten:  - Te koud remt aroma’s - Te warm verliest spanning - Complexe stijlen mogen warmer',
  'service-white-wine:bewaren-en-rijping': 'Goed.  Je beheerst nu professionele serviceprincipes voor witte wijn.  Volgende stap:  **Module 8 — Pairing & Gastronomie**',
  'service-white-wine:decanteren': 'Goed.  Je begrijpt nu:  - wanneer decanteren zinvol is   - welke witte wijnen profiteren   - hoe zuurstof complexiteit opent    Belangrijk voor gevorderde service.',
  'service-white-wine:glaswerk': 'Goed.  Je begrijpt nu hoe glaswerk:  - geur beïnvloedt   - structuur versterkt   - stijlbeleving verandert    Essentieel voor professionele service.',
  'service-white-wine:serveertemperatuur': 'Goed.  Je begrijpt nu:  - waarom temperatuur cruciaal is   - hoe aroma’s beïnvloed worden   - waarom te koud een veelgemaakte fout is   - hoe stijl en temperatuur samenhangen    Professionele service begint hier.',
  'service-wine:bewaren-kelderen': 'Perfect. Je beheerst nu de servicekant van wijn.  Vanaf module 8 ga je wijn koppelen aan gastronomie — de kern van sommelierdenken.',
  'service-wine:decanteren': 'Goed gedaan.  Je begrijpt nu wanneer en waarom wijn wordt gedecanteerd.  Belangrijkste leerpunten:  - jonge wijn profiteert vaak van extra zuurstof - oude wijn wordt vaak gedecanteerd voor sediment - timing is cruciaal om wijn niet te beschadigen  Decanteren is een belangrijk onderdeel van professionele service.',
  'service-wine:glaswerk': 'Goed gedaan.  Je begrijpt nu hoe glaswerk de wijnervaring verandert.  Belangrijkste leerpunten:  - glasvorm beïnvloedt geurontwikkeling - kelkgrootte beïnvloedt zuurstofcontact - opening bepaalt focus en intensiteit  Goed glaswerk is een essentieel service-instrument.',
  'service-wine:serveertemperatuur': 'Goed gedaan.  Je begrijpt nu waarom serveertemperatuur cruciaal is voor wijnbeleving.  Belangrijkste leerpunten:  - temperatuur beïnvloedt aroma en structuur sterk - te koud sluit wijn af - te warm vergroot alcoholgevoel  Correct serveren verhoogt kwaliteit direct.',
  'sour-family-cocktails:margarita': 'Perfect. Je begrijpt nu waarom Margarita één van de belangrijkste sours ter wereld is.',
  'sour-family-cocktails:pisco-sour': 'Perfect. Je begrijpt nu de volledige sour family en kunt structuren vergelijken.',
  'sour-family-cocktails:sidecar': 'Goed. Je begrijpt nu hoe cognac, citrus en likeur samen elegantie bouwen.',
  'sour-family-cocktails:whiskey-sour': 'Sterk. Je begrijpt nu hoe textuur en balans de Whiskey Sour definiëren.',
  'sour-family-cocktails:white-lady': 'Sterk. Je begrijpt nu hoe botanicals en citrus verfijning creëren.',
  'stijl-gastronomie-rose-wine:fruitig-en-sappig': 'Sterk.  Je begrijpt nu waarom fruitige rosé commercieel zo succesvol is.  Belangrijk:  - direct fruit - toegankelijkheid - casual dining',
  'stijl-gastronomie-rose-wine:kruidig-en-droog': 'Goed.  Je begrijpt nu hoe kruidigheid extra diepgang geeft.  Belangrijk:  - complexiteit - kruidigheid - langere inzetbaarheid',
  'stijl-gastronomie-rose-wine:licht-en-fris': 'Goed.  Je begrijpt nu waarom lichte rosé perfect werkt bij verfijnde gerechten.  Belangrijk:  - hoge frisheid - lage body - hoge inzetbaarheid als aperitief',
  'stijl-gastronomie-rose-wine:rose-als-maaltijdwijn': 'Uitstekend. Je begrijpt nu waarom rosé veel serieuzer is dan zijn imago.',
  'stijl-gastronomie-rose-wine:structuur-en-body': 'Sterk.  Je begrijpt nu hoe structuur en body rosé gastronomisch sterker maken.  Belangrijk:  - gewicht - textuur - pairingkracht - stijlverschillen',
  'stijlen-biodynamic:mousserend-per-dagtype': 'Perfect. Je begrijpt nu hoe mousserend zeer gevoelig reageert.',
  'stijlen-biodynamic:port-per-dagtype': 'Perfect. Je begrijpt nu hoe Port biodynamisch kan worden ingezet.',
  'stijlen-biodynamic:rode-wijn-per-dagtype': 'Sterk. Je begrijpt nu hoe rood strategisch te plannen is.',
  'stijlen-biodynamic:rose-per-dagtype': 'Sterk. Je begrijpt nu de biodynamische logica van rosé.',
  'stijlen-biodynamic:witte-wijn-per-dagtype': 'Goed. Je begrijpt nu hoe witte wijn slim te plannen is.',
  'structuur-wine:alcohol': 'Goed gedaan.  Je begrijpt nu de invloed van alcohol op wijn.  Belangrijkste leerpunten:  - alcohol geeft warmte en body - klimaat beïnvloedt alcoholniveau sterk - goede integratie van alcohol is cruciaal voor balans  Alcohol is een belangrijk structuurelement.',
  'structuur-wine:balans': 'Perfect. Je begrijpt nu de structuur van wijn op specialistniveau.  Vanaf module 5 ga je de druivenrassen analyseren — de genetische basis van wijnstijl.',
  'structuur-wine:body': 'Goed gedaan.  Je begrijpt nu hoe body wordt beoordeeld.  Belangrijkste leerpunten:  - body is het gewicht van wijn in de mond - alcohol en extract beïnvloeden body sterk - body helpt bij stijlherkenning en blindproeven  Body is een belangrijke schakel tussen structuur en stijl.',
  'structuur-wine:tannines': 'Goed gedaan.  Je begrijpt nu hoe tannines werken.  Belangrijkste leerpunten:  - tannines komen uit schillen, pitten en hout - tannines geven grip en structuur - tannines spelen een grote rol bij rijping  Tannines zijn essentieel bij rode wijnanalyse.',
  'structuur-wine:zuur': 'Goed gedaan.  Je begrijpt nu waarom zuur essentieel is in wijn.  Belangrijkste leerpunten:  - zuur geeft frisheid en spanning - koel klimaat verhoogt vaak het zuurniveau - zuur is belangrijk voor bewaarpotentieel  Zuur is één van de sterkste kwaliteitsindicatoren.',
  'suiker-stijl-sparkling:brut': 'Goed.  Je begrijpt nu waarom Brut wereldwijd de standaardstijl is.  Belangrijkste leerpunten:  - Goede balans - Breed inzetbaar - Toegankelijk én serieus',
  'suiker-stijl-sparkling:brut-nature': 'Goed gedaan.  Je begrijpt nu waarom Brut Nature de puurste expressie van mousserende wijn is.  Belangrijkste leerpunten:  - Minimaal suikergebruik - Structuur ligt volledig open - Hoge kwaliteit is essentieel',
  'suiker-stijl-sparkling:demi-sec-en-zoet': 'Sterk. Je begrijpt nu hoe suiker en dosage de stijl van mousserende wijn bepalen.',
  'suiker-stijl-sparkling:extra-brut': 'Sterk.  Je begrijpt nu waarom Extra Brut zo populair is in het premiumsegment.  Belangrijkste leerpunten:  - Zeer droog - Meer balans dan Brut Nature - Perfect bij hoge zuren',
  'suiker-stijl-sparkling:extra-dry-dry': 'Sterk.  Je begrijpt nu waarom naamgeving niet altijd gelijkstaat aan smaak.  Belangrijkste leerpunten:  - Extra Dry is zoeter dan Brut - Dry is nog zoeter - Context in pairing is belangrijk',
  'technieken-cocktails:built': 'Goed. Je begrijpt nu hoe eenvoud en precisie samenkomen in built cocktails.',
  'technieken-cocktails:layering': 'Sterk. Je begrijpt nu hoe dichtheid en techniek samenwerken in layered cocktails.',
  'technieken-cocktails:muddling': 'Perfect. Je beheerst nu de basis van cocktailtechnieken.',
  'technieken-cocktails:shaken': 'Goed. Je begrijpt nu waarom shaken essentieel is voor citrus, eiwit en textuur.',
  'technieken-cocktails:stirred': 'Goed. Je begrijpt nu hoe stirred techniek helderheid, controle en elegantie bewaakt.',
  'voorraad-biodynamic:drinkvensters-en-dagtypes': 'Perfect. Je begrijpt nu hoe drinkvensters en dagtypes samenwerken.',
  'voorraad-biodynamic:juiste-fles-juiste-moment': 'Sterk. Je begrijpt nu hoe fleskeuze strategisch werkt.',
  'voorraad-biodynamic:openen-of-wachten': 'Goed. Je begrijpt nu wanneer wachten slimmer is.',
  'voorraad-biodynamic:slim-voorraadbeheer': 'Sterk. Je begrijpt nu hoe voorraadbeheer strategisch wordt.',
  'voorraad-biodynamic:strategic-opening-planning': 'Perfect. Je beheerst nu de strategische kern van biodynamisch drinken.',
  'weer-biodynamic:dynamic-vs-strategic-advice': 'Perfect. Je begrijpt nu de volledige logica achter Dynamic en Strategic Advice en hoe deze direct aansluiten op jouw app-ecosysteem.',
  'weer-biodynamic:luchtdruk-en-expressie': 'Sterk. Je begrijpt nu de mogelijke rol van luchtdruk.',
  'weer-biodynamic:luchtvochtigheid-en-perceptie': 'Goed. Je begrijpt nu hoe luchtvochtigheid subtiele invloed kan hebben.',
  'weer-biodynamic:temperatuur-en-smaak': 'Goed. Je begrijpt nu hoe temperatuur directe invloed heeft op beleving.',
  'weer-biodynamic:weersomslag-en-proeven': 'Sterk. Je begrijpt nu waarom stabiliteit belangrijk is.',
  'wereldstijlen-sparkling:cava': 'Goed gedaan.  Je begrijpt nu waarom Cava één van de sterkste alternatieven voor Champagne is.  Belangrijkste leerpunten:  - Traditionele methode - Eigen Spaanse druiven - Sterke prijs-kwaliteit',
  'wereldstijlen-sparkling:cremant': 'Goed.  Je begrijpt nu de kracht van Crémant als veelzijdige Franse mousserende categorie.  Belangrijkste leerpunten:  - Buiten Champagne - Traditionele methode - Grote regionale diversiteit',
  'wereldstijlen-sparkling:franciacorta': 'Sterk.  Je begrijpt nu waarom Franciacorta internationaal zo hoog wordt gewaardeerd.  Belangrijkste leerpunten:  - Hoog kwaliteitsniveau - Lange rijping - Elegante structuur',
  'wereldstijlen-sparkling:prosecco': 'Sterk.  Je begrijpt nu waarom Prosecco zo succesvol is.  Belangrijkste leerpunten:  - Glera is de kern - Charmat geeft fruitigheid - DOCG staat voor topkwaliteit',
  'wereldstijlen-sparkling:sekt-en-english-sparkling': 'Sterk. Je kent nu de belangrijkste mousserende wereldstijlen buiten Champagne.',
};

export function quizFeedbackForLesson(
  slug: string,
  scorePercent: number,
  moduleSlug?: string
): string {
  if (scorePercent < 60) {
    return 'Herlees de les en probeer de fouten opnieuw.';
  }
  if (moduleSlug) {
    const scoped = LESSON_FEEDBACK[`${moduleSlug}:${slug}`];
    if (scoped) return scoped;
  }
  return LESSON_FEEDBACK[slug] ?? 'Goed gedaan! Je kennis groeit met elke les.';
}

export function quizResultLabel(correctCount: number, totalCount: number): string {
  if (totalCount <= 0) return '';
  if (correctCount === totalCount) return 'Uitstekend';
  if (correctCount / totalCount >= 0.6) return 'Goed bezig';
  return 'Nog oefenen';
}

export type ConfidenceLevel = 'low' | 'medium' | 'high';

export function confidenceFromScore(scorePercent: number): ConfidenceLevel {
  if (scorePercent >= 80) return 'high';
  if (scorePercent >= 60) return 'medium';
  return 'low';
}

export const CONFIDENCE_LABEL: Record<ConfidenceLevel, string> = {
  low: 'Nog oefenen',
  medium: 'Goed bezig',
  high: 'Beheerst',
};
